[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "node dist/src/cli/index.js migrate"
startCommand = "node dist/src/api/index.js"
healthcheckPath = "/healthz"
