export const DIAGNOSTIC_MAX_SERIALIZED_LENGTH = 1_000;
export const DIAGNOSTIC_MAX_STRING_LENGTH = 200;
export const DIAGNOSTIC_OBJECT_BUDGET = 200;
export const DIAGNOSTIC_SANITIZED_MAX_LENGTH = 200;
export const DIAGNOSTIC_ELLIPSIS_TRUNCATION_MARKER = "...[truncated]";
export const DIAGNOSTIC_OBJECT_TRUNCATION_MARKER = "[Truncated]";
